### ISSUE TITLE
feature request: filtering slayer tier enemies when auto-slayer enabled

### ISSUE THREAD

**Issue by jshepler** [Silberdrachi/CanIIdle#12] opened 2021-12-18 16:33 UTC
When auto-slayer is enabled, the game will only assign targets in areas the player can currently access. I think it would be useful to be able to exclude inaccessible targets when determining if the player can idle a tier when auto-slayer is enabled.

**Comment by Silberdrachi** [comment] 2021-12-20 22:54
Not a bad idea. I could add a multi-select dropdown for the different area items. I just would need to figure out how to export which monster is where so i can filter on it.

Prob not going to be updated soon but ill keep it in mind.

**Comment by Silberdrachi** [comment] 2021-12-21 01:57
I lied, i got thinking about it and think i finished what you're looking for. Should be live now.

**Comment by jshepler** [comment] 2021-12-21 12:04
I don't think you understood what I was asking for. Sorry if it wasn't clear enough, but I wasn't asking to only show targets in those areas. That doesn't help with auto-slayer being enabled. The targets for those areas should only be included if the item is currently equipped. Also, it's more about the **summary** showing if the user can idle a tier.

For example, right now, the summary shows that I cannot idle the elite tier. When I go to the slayer tab and select elite, the only target that I can't idle is the Cursed Maiden. She is in the Shrouded Badlands, which requires the Blazing Lantern to be equipped. If I don't have the lantern equipped, auto-slayer will never assign the Cursed Maiden as a target and so I can actually safely idle the elite tier if auto-slayer is enabled.

The app should also:
- Have an option if auto-slayer is enabled. The player has to purchase the option so the game doesn't start with this.
- Have a way to clear the selection(s). This is a problem inherent with multi-selects.
- Persist the auto-slayer toggle and item selection(s) in local storage data.

**Comment by jshepler** [comment] 2021-12-21 12:13
Also, on the slayer tab, instead of hiding targets that are in areas for items not equipped, I think it would be better to mark them somehow so the user can see which targets are not being considered. Maybe a "disabled" effect? Different background color for the row(s)? Faded red? Dunno, just tossing ideas out.

**Comment by Silberdrachi** [comment] 2021-12-21 13:47
So for your first issue, can you not see the overview page updating based on the selections of items? The slayer tier section should be updating the idle-ability status and requirements based on the users selections

for your bullet points
- The option for auto-slayer enabled is selecting an item from the advanced menu
- Multi-selects shouldn't have any problem clearing, just clicking the same item will remove it
- No advanced option will be persisted as the menu is hidden on load and those items could impact idle-ability giving a false sense of safety 

Why would the user want to see the ones that they would not be fighting? Wouldn't that be confusing why its in red, or faded out, or anything other than green if the user can actually idle it? Removing the options that are not what you would be fighting simplifies the screen and shows the user exactly what they will be fighting.

**Comment by jshepler** [comment] 2021-12-21 14:29
The only way the summary got updated is if I selected some other item that I didn't actually have equipped. If auto-slayer is enabled and none of the items are equipped, the player still has access to all the other areas that don't have item requirements. This is all about the slayer tasks that auto-slayer assigns, right? Having auto-slayer enabled doesn't mean the player has to have an item equipped to get tasks. They only get tasks for areas they can currently access given their current gear and slayer level. The game will not assign a task (target) in an area that the player doesn't meet the requirements.

Which makes me think the app should probably also include a setting for current slayer level, or at least the area requirements: 1, 10, 30, 45, 50, 60, 65, 70, 80, 85, 90, 95.

Clicking the same item does not remove it. Maybe it depends on browser, but in firefox and chrome it doesn't do that. I'm talking about if only a single item is selected in the list and you click that item again, it remains selected. I know that control-clicking lets you add and remove multiple items.

As for why a user would want to see the ones they would not be fighting, I was thinking about discoverability. From the point of view of a new player that may not know which, if any, targets were being excluded because they weren't wearing a specific item. It's fine if you think your app shouldn't do that, it was just a thought. I get where you're coming from about simplifying the page.

This isn't really about targeting areas. It's more about excluding areas. A slayer tier that the player wouldn't normally be able to idle (tasks) could then become idle-able when auto-slayer is enabled and an item is NOT equipped.

**Comment by Silberdrachi** [comment] 2021-12-21 14:50
Ill think on this, im opposed to adding all those options to the selections because this is complicating this application far beyond the scope of my intentions.

Ctrl click on every browser ive tested works as intended (ff, chrome, safari)

**Comment by jshepler** [comment] 2021-12-21 15:20
I understand. I would suggest that if you decide not to, then remove what you've added. I think anyone that understands auto-slayer would have expectations the app doesn't currently meet. Since it's specific to slayer, maybe this would be more appropriate for the [idle-slayer](https://sublimedisciple.github.io/idle-slayer.html) app you link to at the bottom of the page? I just like your app better.

I tried control-click that single selection and it worked. I was talking about normal clicking. You can select a single item by a normal click and clicking it again doesn't remove it. I've also noticed over the years, it seems most people don't know how to select multiple items in this control. It's become somewhat rare to find them on pages and most of the ones I've seen have a little blurb to instruct people to use control-click to select multiple items. I don't know how this control is handled on mobile. I typically see checkbox lists for this kind of thing as that's much more intuitive. *shrug* Way off-topic, sorry.

**Comment by Silberdrachi** [comment] 2021-12-23 01:24
Im trying to think of a good way to handle this without making the UI horrible. Ive disabled it for now, while i think of a better way to handle this. So im reopening the issue while i think about how to proceed if i do decide to.

You can try to contact the dev sublimedisciple, but im not sure they are still updating the site, its been a while since it got updated.

Problem is if i dont use a multi-select box this UI would get even worse than i already think it is. Which is why im thinking hard on another way to handle it. Right now the best idea i have is basically a checkbox, a dropdown and a multi-select, just to enable this.

**Comment by jshepler** [comment] 2021-12-23 13:56
Maybe put the auto-slayer stuff into its own section? The current 2-column row that has "Game Mode" and "Advanced Options" could become 3 columns for "Game Mode", "Advanced Options", and "Auto-Slayer". This would help make the advanced options section not get so crowded as well as communicate auto-slayer being a separate "thing".

You could wrap a list of checkboxes in a sized div with overflow-y: scroll. It wouldn't take up much more space than the multi-select, just a little more horizontal space for the checkbox control.

I see you have the slayer cape as an option. There's also the max and completion capes. All 3 have the same effect as far as auto-slayer goes - they give access to all areas. So maybe not have the capes in the list and add another checkbox to indicate player is wearing one of those capes and that when checked, disables or hides the item list.

Another thought, related to the capes. If player is wearing one of the capes, then your app would act the same as if auto-slayer isn't enabled because all targets would be considered. I'm wondering if maybe that could be leveraged somehow to help simplify things.

**Comment by Silberdrachi** [comment] 2022-01-09 18:31
Backed out these changes and im going to close this issue. possibly a future update could have this functionality but having it disabled and out there wont be helpful.

**Closed as completed by Silberdrachi** 2022-01-09 18:31 UTC
