### ISSUE TITLE
Furious Horned Elite Horn Shots Calculation

### ISSUE THREAD

**Issue by Nazacra** [Silberdrachi/CanIIdle#16] opened 2022-01-16 23:11 UTC
It looks like the damage calculation in CanIIdle for Furious Horned Elite's Horn Shots is wrong.

In game max hit (magic style, 30% DR):
![image](https://user-images.githubusercontent.com/8422359/149681658-2672bb3b-04ea-45f1-aee6-ddeba78fd8ba.png)

CanIIdle  (magic style, 30% DR):
![image](https://user-images.githubusercontent.com/8422359/149681708-f6958a9b-0959-4981-9aa8-49a8d875ef95.png)

Wiki:
![image](https://user-images.githubusercontent.com/8422359/149681742-63d939cb-fcdc-4270-95f7-6aa1dd42b564.png)

At first I thought that it was just combining the three hits into one big one (which would be wrong because Auto Eat can heal between the hits of Horn Shots), but that doesn't seem to add up to the correct number either, as that would be 397 * 0.6 * 3 = 714.6.

Regardless, unless I am missing something it seems to be calculating wrong.

**Comment by Silberdrachi** [comment] 2022-01-16 23:15
yeah, i can guess what the problem is. i just dont have special handling for that attack. prob can fix in a couple minutes when i have some time free tonight.

**Comment by Silberdrachi** [comment] 2022-01-17 00:04
Should be fixed

**Closed as completed by Silberdrachi** 2022-01-17 00:04 UTC
